### ISSUE TITLE
Update metadata

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-major-works-and-events#16]
Running the pages through a [meta tag checker](https://metatags.io), it's placeholder data still

<img width="564" alt="Screenshot 2020-07-03 at 10 35 38" src="https://user-images.githubusercontent.com/10854265/86455720-f07fe600-bd18-11ea-92ff-8445e1de1b3f.png">

<img width="577" alt="Screenshot 2020-07-03 at 10 35 49" src="https://user-images.githubusercontent.com/10854265/86455740-f70e5d80-bd18-11ea-9f01-2f51dda42c27.png">

Please can the metadata be updated so that it's dynamic:
* Meta title: Umbraco page title
* Meta description: Public transport information on bus, train, tram, cycling and ticketing for the West Midlands region
* Meta image: the image used in the placeholder, for instance: ![](https://beta.wmnetwork.co.uk/media/judkvckc/plan-ahead-cones.png)

**Comment by rolorogan** [comment]
@mrmjprice This is now fixed
