### ISSUE TITLE
Sign up for updates

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-major-works-and-events#21]
Where we have 'stay up to date' box on the right, please remove email address text field, and add a button 'sign up for updates' and linkit will link to campaign monitor.

**Comment by RachelFoy** [comment]
Could I have an update on when this will be added? Currently adding info as a text back meaning it is on the left when should be under travel tips on the right

**Comment by houbly** [comment]
This change has now been pushed to live so I will close this issue
