### ISSUE TITLE
Advice to keep you moving rename 

### ISSUE THREAD

**Issue by RachelFoy** [wmcadigital/wmn-major-works-and-events#27]
Can this be amended to "Latest Works" - the subpages will then be updates on works happening in each scheme. 

We would still like to have the advice to keep moving for each mode, e.g drivers and cyclists. So if this could be duplicated and when creating the subpage we select if it is for advice and works. 

Also only the latest works subpages should show in the overview section at the top

**Comment by RachelFoy** [comment]
Reviewed with Andy and can we actually just have the "Advice to keep to moving" renamed to "Latest Works"

**Comment by houbly** [comment]
This change has now been pushed to live so I will close this issue
