### ISSUE TITLE
Stay up to date general widget on landing page

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-major-works-and-events#38]
Please add Stay up to date widget (with [email and postcode](https://designsystem.wmnetwork.co.uk/patterns/content-cards/) - the general one which collapses and extends) to the [landing page of major works](https://dev-wmnetwork.s1.umbraco.io/plan-your-journey/major-roadworks-and-events/).

**Comment by houbly** [comment]
This change has now been pushed to live so I will close this issue
