### ISSUE TITLE
Date on subpage

### ISSUE THREAD

**Issue by RachelFoy** [wmcadigital/wmn-major-works-and-events#40]
When I create a subpage the date for the work is wrong. 

![image](https://user-images.githubusercontent.com/68917167/96736781-deec4800-13b4-11eb-91f8-c7afcbcdf842.png)

Could we have 'Lasts Until' changed the 'Ends:' on all? This works better when we have ongoing. 

And can the subpages have a different date range than the main events pages?

**Comment by houbly** [comment]
Closing this as it has gone live
